version: '3'
services:
  backend_2:
    container_name: backend_2
    build:
      context: ./backend
      dockerfile: Dockerfile.1
    ports: 
      - "8888:8888"
    env_file: 
      - ./backend/.env.1
    volumes:
      - ./backend:/app
  
  frontend_2:
    container_name: frontend_2
    build:
      context: ./frontend
      dockerfile: Dockerfile.1
    ports: 
      - "4000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend_2
volumes:
  data: