version: '3'
services:
  backend:
    build: ./backend
    ports: 
      - "9999:9999"
    volumes:
      - ./backend:/app
  
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
volumes:
  data: