version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports: 
      - "9999:9999"
    env_file: 
      - ./backend/.env
    volumes:
      - ./backend:/app
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
volumes:
  data: